name: rodrigoff
description: web development and random stuff
meta_description: "blog.rodrigoff.com"

aboutPage: false

markdown: redcarpet
highlighter: pygments

paginate: 20
baseurl: /
domain_name: 'http://blog.rodrigoff.com'
google_analytics: 'UA-67517193-1'
disqus: false
disqus_shortname: 'your-disqus-shortname'

# Details for the RSS feed generator
url:            'http://your-blog-url.example.com'
author:         'Rodrigo F. Fernandes'
authorTwitter:  'rodrigoff'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
